### ISSUE TITLE
Put Stagger inside Stagger cause warning

### ISSUE THREAD

**Issue by rizkiandrianto** [natenorberg/react-css-stagger#1]
I want to make inception animation, but there's a warning like this:

![image](https://cloud.githubusercontent.com/assets/2457820/23584262/81e0adf4-018e-11e7-89f2-2755fe7e812d.png)

Did you have any suggestion?

**Comment by natenorberg** [comment]
Hmm, thanks for finding this. If I copy the source code into another project it doesn't have this error, so it must be something with my webpack build.

I'll try to look into it.

**Comment by rizkiandrianto** [comment]
Any updates @natenorberg ? :)

**Comment by natenorberg** [comment]
I think my commit fixed the issue, but it broke the tests. As soon as I can get that resolved I'll bump the version.

**Comment by natenorberg** [comment]
Alright. Should be fixed in version 0.0.4

Thanks for finding that

**Comment by rizkiandrianto** [comment]
Stil the same :neutral_face: @natenorberg
